/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace FiniteField {
  export type ZpStruct = { value: BigNumberish };

  export type ZpStructOutput = [value: bigint] & { value: bigint };
}

export declare namespace QuadraticExtension {
  export type Zp_2Struct = { a: FiniteField.ZpStruct; b: FiniteField.ZpStruct };

  export type Zp_2StructOutput = [
    a: FiniteField.ZpStructOutput,
    b: FiniteField.ZpStructOutput
  ] & { a: FiniteField.ZpStructOutput; b: FiniteField.ZpStructOutput };
}

export interface QuadraticExtensionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createElement"
      | "div"
      | "equals"
      | "inverse"
      | "mul"
      | "mul_nonres"
      | "sub"
      | "sum"
      | "zero"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createElement",
    values: [FiniteField.ZpStruct, FiniteField.ZpStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "div",
    values: [QuadraticExtension.Zp_2Struct, QuadraticExtension.Zp_2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "equals",
    values: [QuadraticExtension.Zp_2Struct, QuadraticExtension.Zp_2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "inverse",
    values: [QuadraticExtension.Zp_2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "mul",
    values: [QuadraticExtension.Zp_2Struct, QuadraticExtension.Zp_2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_nonres",
    values: [QuadraticExtension.Zp_2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "sub",
    values: [QuadraticExtension.Zp_2Struct, QuadraticExtension.Zp_2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "sum",
    values: [QuadraticExtension.Zp_2Struct, QuadraticExtension.Zp_2Struct]
  ): string;
  encodeFunctionData(functionFragment: "zero", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createElement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "div", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "equals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inverse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul_nonres", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sum", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zero", data: BytesLike): Result;
}

export interface QuadraticExtension extends BaseContract {
  connect(runner?: ContractRunner | null): QuadraticExtension;
  waitForDeployment(): Promise<this>;

  interface: QuadraticExtensionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createElement: TypedContractMethod<
    [a: FiniteField.ZpStruct, b: FiniteField.ZpStruct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;

  div: TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;

  equals: TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [boolean],
    "view"
  >;

  inverse: TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;

  mul: TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;

  mul_nonres: TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;

  sub: TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;

  sum: TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;

  zero: TypedContractMethod<[], [QuadraticExtension.Zp_2StructOutput], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createElement"
  ): TypedContractMethod<
    [a: FiniteField.ZpStruct, b: FiniteField.ZpStruct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "div"
  ): TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "equals"
  ): TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "inverse"
  ): TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mul"
  ): TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mul_nonres"
  ): TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "sub"
  ): TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "sum"
  ): TypedContractMethod<
    [x: QuadraticExtension.Zp_2Struct, y: QuadraticExtension.Zp_2Struct],
    [QuadraticExtension.Zp_2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "zero"
  ): TypedContractMethod<[], [QuadraticExtension.Zp_2StructOutput], "view">;

  filters: {};
}
