/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BigNumbers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BigNumbers__factory>;
    getContractFactory(
      name: "BigFiniteField",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BigFiniteField__factory>;
    getContractFactory(
      name: "FiniteField",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiniteField__factory>;
    getContractFactory(
      name: "QuadraticExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.QuadraticExtension__factory>;
    getContractFactory(
      name: "SexticExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SexticExtension__factory>;
    getContractFactory(
      name: "TwelveExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TwelveExtension__factory>;

    getContractAt(
      name: "BigNumbers",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BigNumbers>;
    getContractAt(
      name: "BigFiniteField",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BigFiniteField>;
    getContractAt(
      name: "FiniteField",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FiniteField>;
    getContractAt(
      name: "QuadraticExtension",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.QuadraticExtension>;
    getContractAt(
      name: "SexticExtension",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SexticExtension>;
    getContractAt(
      name: "TwelveExtension",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TwelveExtension>;

    deployContract(
      name: "BigNumbers",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigNumbers>;
    deployContract(
      name: "BigFiniteField",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigFiniteField>;
    deployContract(
      name: "FiniteField",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FiniteField>;
    deployContract(
      name: "QuadraticExtension",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.QuadraticExtension>;
    deployContract(
      name: "SexticExtension",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SexticExtension>;
    deployContract(
      name: "TwelveExtension",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TwelveExtension>;

    deployContract(
      name: "BigNumbers",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigNumbers>;
    deployContract(
      name: "BigFiniteField",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigFiniteField>;
    deployContract(
      name: "FiniteField",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FiniteField>;
    deployContract(
      name: "QuadraticExtension",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.QuadraticExtension>;
    deployContract(
      name: "SexticExtension",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SexticExtension>;
    deployContract(
      name: "TwelveExtension",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TwelveExtension>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
