/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BigNumbers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BigNumbers__factory>;
    getContractFactory(
      name: "Curve",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Curve__factory>;
    getContractFactory(
      name: "BigFiniteField",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BigFiniteField__factory>;
    getContractFactory(
      name: "QuadraticExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.QuadraticExtension__factory>;
    getContractFactory(
      name: "SexticExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SexticExtension__factory>;
    getContractFactory(
      name: "TwelveExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TwelveExtension__factory>;
    getContractFactory(
      name: "PointZp_12",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PointZp_12__factory>;
    getContractFactory(
      name: "PointZp_2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PointZp_2__factory>;
    getContractFactory(
      name: "PointZp",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PointZp__factory>;

    getContractAt(
      name: "BigNumbers",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BigNumbers>;
    getContractAt(
      name: "Curve",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Curve>;
    getContractAt(
      name: "BigFiniteField",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BigFiniteField>;
    getContractAt(
      name: "QuadraticExtension",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.QuadraticExtension>;
    getContractAt(
      name: "SexticExtension",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SexticExtension>;
    getContractAt(
      name: "TwelveExtension",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TwelveExtension>;
    getContractAt(
      name: "PointZp_12",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PointZp_12>;
    getContractAt(
      name: "PointZp_2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PointZp_2>;
    getContractAt(
      name: "PointZp",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PointZp>;

    deployContract(
      name: "BigNumbers",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigNumbers>;
    deployContract(
      name: "Curve",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Curve>;
    deployContract(
      name: "BigFiniteField",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigFiniteField>;
    deployContract(
      name: "QuadraticExtension",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.QuadraticExtension>;
    deployContract(
      name: "SexticExtension",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SexticExtension>;
    deployContract(
      name: "TwelveExtension",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TwelveExtension>;
    deployContract(
      name: "PointZp_12",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointZp_12>;
    deployContract(
      name: "PointZp_2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointZp_2>;
    deployContract(
      name: "PointZp",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointZp>;

    deployContract(
      name: "BigNumbers",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigNumbers>;
    deployContract(
      name: "Curve",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Curve>;
    deployContract(
      name: "BigFiniteField",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigFiniteField>;
    deployContract(
      name: "QuadraticExtension",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.QuadraticExtension>;
    deployContract(
      name: "SexticExtension",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SexticExtension>;
    deployContract(
      name: "TwelveExtension",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TwelveExtension>;
    deployContract(
      name: "PointZp_12",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointZp_12>;
    deployContract(
      name: "PointZp_2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointZp_2>;
    deployContract(
      name: "PointZp",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointZp>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
