/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type BigNumberStruct = {
  val: BytesLike;
  neg: boolean;
  bitlen: BigNumberish;
};

export type BigNumberStructOutput = [
  val: string,
  neg: boolean,
  bitlen: bigint
] & { val: string; neg: boolean; bitlen: bigint };

export type ZpStruct = { value: BigNumberStruct };

export type ZpStructOutput = [value: BigNumberStructOutput] & {
  value: BigNumberStructOutput;
};

export type Point_ZpStruct = {
  pointType: BigNumberish;
  x: ZpStruct;
  y: ZpStruct;
};

export type Point_ZpStructOutput = [
  pointType: bigint,
  x: ZpStructOutput,
  y: ZpStructOutput
] & { pointType: bigint; x: ZpStructOutput; y: ZpStructOutput };

export interface PointZpInterface extends Interface {
  getFunction(
    nameOrSignature: "add" | "double" | "multiply" | "negate" | "newPoint"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [Point_ZpStruct, Point_ZpStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "double",
    values: [Point_ZpStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "multiply",
    values: [Point_ZpStruct, BigNumberStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "negate",
    values: [Point_ZpStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "newPoint",
    values: [BigNumberish, ZpStruct, ZpStruct]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "double", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "negate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newPoint", data: BytesLike): Result;
}

export interface PointZp extends BaseContract {
  connect(runner?: ContractRunner | null): PointZp;
  waitForDeployment(): Promise<this>;

  interface: PointZpInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<
    [self: Point_ZpStruct, other: Point_ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;

  double: TypedContractMethod<
    [self: Point_ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;

  multiply: TypedContractMethod<
    [self: Point_ZpStruct, k: BigNumberStruct],
    [Point_ZpStructOutput],
    "view"
  >;

  negate: TypedContractMethod<
    [self: Point_ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;

  newPoint: TypedContractMethod<
    [pointType: BigNumberish, x: ZpStruct, y: ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [self: Point_ZpStruct, other: Point_ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "double"
  ): TypedContractMethod<
    [self: Point_ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "multiply"
  ): TypedContractMethod<
    [self: Point_ZpStruct, k: BigNumberStruct],
    [Point_ZpStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "negate"
  ): TypedContractMethod<
    [self: Point_ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "newPoint"
  ): TypedContractMethod<
    [pointType: BigNumberish, x: ZpStruct, y: ZpStruct],
    [Point_ZpStructOutput],
    "view"
  >;

  filters: {};
}
